package cs213.photoAlbum.simpleview;

import cs213.photoAlbum.control.Control;
import cs213.photoAlbum.model.Photo;
import cs213.photoAlbum.model.PhotoAlbum;
import cs213.photoAlbum.model.Tag;
import cs213.photoAlbum.util.PhotoException;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Mike Newman
 */
public class PhotoViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form PhotoViewPanel
     */
    public PhotoViewPanel(Control control, Photo photo, PhotoAlbum album) {
        this.photo = photo;
        this.album = album;
        this.control = control;
        photoList = album.getPhotoList();
        index = photoList.indexOf(photo);
        initComponents();
        AddTagDialog.setLocationRelativeTo(null);
        DeleteTagDialog.setLocationRelativeTo(null);
        displayPhoto();
    }
    
    private void displayPhoto() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(photo.getFileName()));
        } catch (IOException e) { }
        ImageIcon icon = new ImageIcon(img.getScaledInstance(410, 265, Image.SCALE_SMOOTH));
        ImageDisplay.setIcon(icon);
        setLabels();
    }
    
    private void setLabels() {
        String caption = photo.getCaption();
        if (caption.equals(""))  caption = " ";
        photoCaption.setText(caption);
        
        if (photo.getDate() == null) {
            photoDate.setText(" ");
        } else {
            DateFormat df = new SimpleDateFormat("MM/dd/yyyy-HH:mm:ss");
            String date = df.format(photo.getDate().getTime());
            photoDate.setText(date);
        }
        
        String tags = photo.getTagList().toString();
        if (tags.equals("") || tags.equals("[]")) {
            tags = " ";
        } else {
            tags = tags.substring(1, tags.length()-1);
        }
        photoTagList.setText(tags);
        photoTagList.setToolTipText(tags);
    }
    
    
    // get current album photo being viewed is within
    public PhotoAlbum getAlbum() {
        return this.album;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        AddTagDialog = new javax.swing.JDialog();
        btnAddTagOk = new javax.swing.JButton();
        btnAddTagCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TagTypeField = new javax.swing.JTextField();
        TagValueField = new javax.swing.JTextField();
        AddTagErrorLabel = new javax.swing.JLabel();
        DeleteTagDialog = new javax.swing.JDialog();
        btnDeleteTagOk = new javax.swing.JButton();
        btnDeleteTagCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ddlTags = new javax.swing.JComboBox();
        DeleteTagErrorLabel = new javax.swing.JLabel();
        PhotoPanel = new javax.swing.JPanel();
        ImageDisplay = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnAddTag = new javax.swing.JButton();
        btnDeleteTag = new javax.swing.JButton();
        photoCaption = new javax.swing.JLabel();
        photoDate = new javax.swing.JLabel();
        photoTagList = new javax.swing.JLabel();

        AddTagDialog.setTitle("Add Tag");
        AddTagDialog.setMinimumSize(new java.awt.Dimension(342, 190));
        AddTagDialog.setResizable(false);

        btnAddTagOk.setBackground(new java.awt.Color(0, 51, 204));
        btnAddTagOk.setForeground(new java.awt.Color(254, 254, 254));
        btnAddTagOk.setText("Ok");
        btnAddTagOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTagOkActionPerformed(evt);
            }
        });

        btnAddTagCancel.setBackground(new java.awt.Color(0, 51, 204));
        btnAddTagCancel.setForeground(new java.awt.Color(254, 254, 254));
        btnAddTagCancel.setText("Cancel");
        btnAddTagCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTagCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Type:");

        jLabel2.setText("Value:");

        AddTagErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout AddTagDialogLayout = new javax.swing.GroupLayout(AddTagDialog.getContentPane());
        AddTagDialog.getContentPane().setLayout(AddTagDialogLayout);
        AddTagDialogLayout.setHorizontalGroup(
            AddTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTagDialogLayout.createSequentialGroup()
                .addGroup(AddTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AddTagDialogLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnAddTagOk, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnAddTagCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddTagDialogLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(AddTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(AddTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TagValueField, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(AddTagErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TagTypeField))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        AddTagDialogLayout.setVerticalGroup(
            AddTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddTagDialogLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(AddTagErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TagTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(AddTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TagValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(AddTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTagCancel)
                    .addComponent(btnAddTagOk))
                .addContainerGap())
        );

        DeleteTagDialog.setTitle("Add Tag");
        DeleteTagDialog.setMaximumSize(new java.awt.Dimension(342, 150));
        DeleteTagDialog.setMinimumSize(new java.awt.Dimension(342, 150));
        DeleteTagDialog.setPreferredSize(new java.awt.Dimension(342, 150));
        DeleteTagDialog.setResizable(false);

        btnDeleteTagOk.setBackground(new java.awt.Color(0, 51, 204));
        btnDeleteTagOk.setForeground(new java.awt.Color(254, 254, 254));
        btnDeleteTagOk.setText("Ok");
        btnDeleteTagOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTagOkActionPerformed(evt);
            }
        });

        btnDeleteTagCancel.setBackground(new java.awt.Color(0, 51, 204));
        btnDeleteTagCancel.setForeground(new java.awt.Color(254, 254, 254));
        btnDeleteTagCancel.setText("Cancel");
        btnDeleteTagCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTagCancelActionPerformed(evt);
            }
        });

        jLabel4.setText("Tag:");

        DeleteTagErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout DeleteTagDialogLayout = new javax.swing.GroupLayout(DeleteTagDialog.getContentPane());
        DeleteTagDialog.getContentPane().setLayout(DeleteTagDialogLayout);
        DeleteTagDialogLayout.setHorizontalGroup(
            DeleteTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteTagDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(DeleteTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DeleteTagDialogLayout.createSequentialGroup()
                        .addComponent(btnDeleteTagOk, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnDeleteTagCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteTagDialogLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DeleteTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteTagErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(ddlTags, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(57, 57, 57))
        );
        DeleteTagDialogLayout.setVerticalGroup(
            DeleteTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteTagDialogLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(DeleteTagErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeleteTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ddlTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 56, Short.MAX_VALUE)
                .addGroup(DeleteTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteTagCancel)
                    .addComponent(btnDeleteTagOk))
                .addContainerGap())
        );

        DeleteTagDialog.getAccessibleContext().setAccessibleName("Delete Tag");

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(580, 330));

        ImageDisplay.setMaximumSize(new java.awt.Dimension(410, 250));
        ImageDisplay.setMinimumSize(new java.awt.Dimension(410, 250));
        ImageDisplay.setPreferredSize(new java.awt.Dimension(410, 238));

        javax.swing.GroupLayout PhotoPanelLayout = new javax.swing.GroupLayout(PhotoPanel);
        PhotoPanel.setLayout(PhotoPanelLayout);
        PhotoPanelLayout.setHorizontalGroup(
            PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PhotoPanelLayout.setVerticalGroup(
            PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnPrev.setBackground(new java.awt.Color(0, 51, 204));
        btnPrev.setForeground(new java.awt.Color(254, 254, 254));
        btnPrev.setText("<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(0, 51, 204));
        btnNext.setForeground(new java.awt.Color(254, 254, 254));
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnAddTag.setBackground(new java.awt.Color(0, 51, 204));
        btnAddTag.setForeground(new java.awt.Color(254, 254, 254));
        btnAddTag.setText("Add Tag");
        btnAddTag.setMaximumSize(new java.awt.Dimension(100, 27));
        btnAddTag.setMinimumSize(new java.awt.Dimension(100, 27));
        btnAddTag.setPreferredSize(new java.awt.Dimension(100, 27));
        btnAddTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTagActionPerformed(evt);
            }
        });

        btnDeleteTag.setBackground(new java.awt.Color(0, 51, 204));
        btnDeleteTag.setForeground(new java.awt.Color(254, 254, 254));
        btnDeleteTag.setText("Delete Tag");
        btnDeleteTag.setMaximumSize(new java.awt.Dimension(100, 27));
        btnDeleteTag.setMinimumSize(new java.awt.Dimension(100, 27));
        btnDeleteTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTagActionPerformed(evt);
            }
        });

        photoCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoCaption.setText("  ");
        photoCaption.setAutoscrolls(true);

        photoDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoDate.setText("  ");
        photoDate.setAutoscrolls(true);

        photoTagList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoTagList.setText("  ");
        photoTagList.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrev)
                        .addGap(12, 12, 12)
                        .addComponent(PhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddTag, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteTag, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(photoCaption, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(photoDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(photoTagList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(90, 90, 90)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnPrev))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(PhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(photoCaption)
                .addGap(3, 3, 3)
                .addComponent(photoDate)
                .addGap(3, 3, 3)
                .addComponent(photoTagList)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
    }

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {
        if(index == 0) {
            index = photoList.size()-1;
//            return;
        } else {
            index --;
        }
        photo = photoList.get(index);
        displayPhoto();
    }
    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {
        if (photoList.size() <= index+1) {
            index = 0;
//            return;
        } else {
            index++;
        }
        photo = photoList.get(index);
        displayPhoto();
    }

    private void btnDeleteTagActionPerformed(java.awt.event.ActionEvent evt) {
        
        LinkedList<Tag> tagList = photo.getTagList();
        for(Tag tag : tagList) {
            ddlTags.addItem(tag);
        }
        DeleteTagDialog.setVisible(true);
    }

    private void btnAddTagActionPerformed(java.awt.event.ActionEvent evt) {
        AddTagDialog.setVisible(true);
    }

    private void btnAddTagCancelActionPerformed(java.awt.event.ActionEvent evt) {
        AddTagDialog.setVisible(false);
        TagTypeField.setText("");
        TagValueField.setText("");
    }

    private void btnAddTagOkActionPerformed(java.awt.event.ActionEvent evt) {
        
        try {
            control.addTag(photo.getFileName(), TagTypeField.getText(), TagValueField.getText());
        } catch (Exception e) {
            if (e instanceof PhotoException) {
                AddTagErrorLabel.setText("Error: Invalid photo");
            } else {
                AddTagErrorLabel.setText("Error: Tag already exists for photo");
            }
            return;
        }
        
        AddTagDialog.setVisible(false);
        TagTypeField.setText("");
        TagValueField.setText("");
        setLabels();
    }

    private void btnDeleteTagOkActionPerformed(java.awt.event.ActionEvent evt) {
        
        // delete tag stuff
        Tag tag = (Tag)ddlTags.getSelectedItem();
        try {
            control.deleteTag(photo.getFileName(), tag.getType(), tag.getValue());
        } catch (Exception e) {
             if (e instanceof PhotoException) {
                DeleteTagErrorLabel.setText("Error: Invalid photo");
            } else {
                DeleteTagErrorLabel.setText("Error: Tag doesn't exist");
            }
            return;
        }
        ddlTags.removeAllItems();
        DeleteTagDialog.setVisible(false);
        setLabels();
    }

    private void btnDeleteTagCancelActionPerformed(java.awt.event.ActionEvent evt) {
        ddlTags.removeAllItems();
        DeleteTagDialog.setVisible(false);
    }

	private Photo photo;
	private PhotoAlbum album;
	private ArrayList<Photo> photoList;
	private Control control;
	private int index;

	private javax.swing.JDialog AddTagDialog;
    private javax.swing.JLabel AddTagErrorLabel;
    private javax.swing.JDialog DeleteTagDialog;
    private javax.swing.JLabel DeleteTagErrorLabel;
    private javax.swing.JLabel ImageDisplay;
    private javax.swing.JPanel PhotoPanel;
    private javax.swing.JTextField TagTypeField;
    private javax.swing.JTextField TagValueField;
    private javax.swing.JButton btnAddTag;
    private javax.swing.JButton btnAddTagCancel;
    private javax.swing.JButton btnAddTagOk;
    private javax.swing.JButton btnDeleteTag;
    private javax.swing.JButton btnDeleteTagCancel;
    private javax.swing.JButton btnDeleteTagOk;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JComboBox ddlTags;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel photoCaption;
    private javax.swing.JLabel photoDate;
    private javax.swing.JLabel photoTagList;
    
}
